
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>员工信息列表</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <script src="/js/jquery-1.4.1.js" type="text/javascript"></script>
   <script src="/js/jquery-1.9.1.min.js" type="text/javascript"></script>
   <script src="/js/DatePicker/WdatePicker.js" type="text/javascript"></script>
   <script type="text/javascript">

		function searchuserinfo()
		{
		   var name=$('#name').val();
		   if(name==""){
				alert('请输入员工姓名');
				return;
			   }
		   window.location.href="/Employee/employee?name="+name;
		}
		//删除信息
		function employeedel(uid)
		{
			if(confirm("确定要删除该条信息吗？")){
				 $.ajax({
					  	type: "POST",
					    url: "/Employee/employdel",
					    data:"uid="+uid,
					    success: function(msg){
					    if(msg==0){
					        alert("删除信息成功！");
				        }
					    else if(msg==1){//说明token过期或者token错误，用户需要重新登录
		  			       	window.location.href='/Index/index';
		  			        return;   
						}else
			         	{
			         	    alert("删除失败！");
			            }
					    window.location.href='/Employee/employee';
					}
				});
			}
		}
   </script>
   <style type="text/css">
		.searchinput{margin-top:10px;width:100px;}
		.searchselect{margin-top:10px;width:120px;}
   </style>
</head>
<body class="fixed-top">
   <?php require APPLICATION_PATH.'/views/scripts/index/header.phtml';?>
   <div id="container" class="row-fluid">
      <?php require APPLICATION_PATH.'/views/scripts/index/mainleft.phtml';?>
      
      <div id="main-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                   <h3 class="page-title">员工信息</h3>
                   <ul class="breadcrumb">
                       <li>
                           <a href="/Medicrm/default">首页</a>
                           <span class="divider">/</span>
                       </li>
                       <li>
                           <a href="/Employee/employee">员工信息管理</a>
                           <span class="divider">/</span>
                       </li>
                       <li class="active">员工信息</li>
                   </ul>
               </div>
            </div>
           
            <div id="page-wraper">
                <div class="row-fluid">
                    <div class="span12">
                        <div class="widget blue">
                            <div class="widget-title">
                                <h4><i class="icon-reorder"></i>员工信息列表</h4>
                            </div>
                <div style="margin-left:20px;">
                <table>
                  	<tr>
                        <td>
                            &nbsp;<b>员工姓名：</b>
                        </td>
                        <td>
                            <input type="text" id="name" name="name" class="searchinput" value="<?=$this->name?>" />
                        </td>
                        <td>
                            &nbsp;&nbsp;&nbsp;
                            <a href="javascript:void(0)" class="btn" style="text-align:center;color:black;width:50px;" onclick="searchuserinfo();">查询</a>
                        </td>
                        <td>
                            &nbsp;&nbsp;&nbsp;
                            <?php if($_SESSION['loginuser']['crm_EmployID']==1){?>
                            <a href="/Employee/persinfo" class="btn" style="text-align:center;color:black;width:80px;">添加员工</a>
                            <?php }?>
                            &nbsp;&nbsp;&nbsp;
                        </td>
                    </tr>
                </table>
           		 </div>
                            <div class="widget-body">
                                <table class="table table-striped table-bordered table-advance table-hover">
                                    <thead>
                                    <tr>
                                        <th style="text-align:center;"><i class=""></i> 员工姓名</th>
                                        <th style="text-align:center;"><i class=""></i> 员工登录名</th>
                                        <th style="text-align:center;"><i class=""></i> 员工性别</th>
                                        <th style="text-align:center;"><i class=""></i> 员工电话</th>
                                        <th style="text-align:center;"><i class=""></i> 员工地址</th>
                                        <th style="text-align:center;"><i class=""></i> 员工QQ</th>
                                        <th style="text-align:center;"><i class=""></i> 员工邮箱</th>
                                        <th style="text-align:center;"><i class=""></i> 头像缩略图</th>
                                        <th style="text-align:center;"></th>
                                    </tr>
                                    </thead>
                                    <?php foreach ($this->employlst as $employ){?>
                                    <tr>
                                        <td style="text-align:center;"><?=$employ["crm_Name"]?></td>
                                        <td style="text-align:center;"><?=$employ["crm_LoginName"]?></td>
                                        <td style="text-align:center;"><?=$employ["crm_Gender"]=="0"?"女":"男"?></td>
                                        <td style="text-align:center;"><?=$employ["crm_UserPhone"]?></td>
                                        <td style="text-align:center;"><?=$employ["crm_UserAddress"]?></td>
                                        <td style="text-align:center;"><?=$employ["crm_UserQQ"]?></td>
                                        <td style="text-align:center;"><?=$employ["crm_UserEmail"]?></td>
                                        <td style="text-align:center;"><img src="<?=empty($employ["crm_UserImg"])?"/images/avatar-mini.png":$employ["crm_UserImg"]?>" style="width:50px;height:50px;"/></td>
                                        <td style="text-align:center;">
                                         	<a title="查看" href="/Employee/persinfo?upd=<?=$employ['crm_EmployID']?>&ck=1"><button class="btn btn-success"><i class="icon-edit"></i></button></a>
                                         	<?php if($_SESSION['loginuser']['crm_EmployID']==1){?>
                                         	<a title="编辑" href="/Employee/persinfo?upd=<?=$employ['crm_EmployID']?>" ><button class="btn btn-primary"><i class="icon-pencil"></i></button></a>
                                            <a title="删除" onclick="employeedel(<?=$employ['crm_EmployID']?>);" href="javascript:void(0);" ><button class="btn btn-danger"><i class="icon-trash "></i></button></a>
                                         	<?php }?>
                                            
                                        </td>
                                    </tr>
                                    <?php }?>
                                </table>
                                <br/>
                               	<?php if ($this->lbcount>10){
								 	require APPLICATION_PATH.'/views/scripts/index/pageclass.php';
								 	$p=new PageClass();
								 	$pagemsg=$p->pagemsg($this->spage,$this->cpage,"/Employee/employee",$this->urlpara);
									}
									echo "<div style='width:90%;margin:0 auto;text-align:right;'>$pagemsg</div>";
								 ?> 
								<?php if ($this->lbcount<=0){
									require APPLICATION_PATH.'/views/scripts/index/noticemsg.phtml';
									}
								?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>     
         </div>
      </div>
   </div>
   <?php require APPLICATION_PATH.'/views/scripts/index/bottom.phtml';?>
   <script type="text/javascript" src="/js/jquery-ui-1.9.2.custom.min.js"></script>
   <script>
        function loadfun()
        {
        	 $("#ygxx").attr("class", "active");
        	 $("#yggl").attr("class", "active");
        }
        loadfun();
   </script>
</body>
</html>
