<!DOCTYPE html>
<!-- saved from url=(0050)http://www.js-css.cn/divcss/admin/metro/login.html -->
<html lang="en"><!--<![endif]--><!-- BEGIN HEAD --><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <meta charset="utf-8">
   <title>医库软件CRM管理登录</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport">
   <meta content="" name="description">
   <meta content="" name="author">
   <link href="/css/bootstrap.min.css" rel="stylesheet">
   <link href="/css/bootstrap-responsive.min.css" rel="stylesheet">
   <link href="/css/font-awesome.css" rel="stylesheet">
   <link href="/css/style.css" rel="stylesheet">
   <link href="/css/style-responsive.css" rel="stylesheet">
   <link href="/css/style-default.css" rel="stylesheet" id="style_color">
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="lock">
    <div class="lock-header">
        <!--logo加载开始-->
        <a class="center" id="logo" href="http://medicool.cn">
            <img class="center" alt="logo" src="/images/logo.png">
        </a>
        <!-- logo加载结束 -->
    </div>
    <div class="login-wrap">
        <div class="metro single-size red">
            <div class="locked">
                <i class="icon-lock"></i>
                <span>登录</span>
            </div>
        </div>
        <form action="/Index/default" method="post">
            <div class="metro double-size green">
                <div class="input-append lock-input">
                    <input type="text" name="username" placeholder="Username">
                </div>
            </div>
            <div class="metro double-size yellow">
                <div class="input-append lock-input">
                    <input type="password" name="userpwd" placeholder="Password">
                </div>
            </div>
            <div class="metro single-size terques login">
                <button type="submit" class="btn login-btn">
                                                登录
                    <i class=" icon-long-arrow-right"></i>
                </button>
            </div>
            <?php if(!empty($this->logmsg)){?>
             <div class="metro double-size blue" style="width:40%;line-height:100px;height:100px;margin-top:10px;">
                <i class="icon-warning-sign"></i>
                <span><?=$this->logmsg?></span>
            </div>
            <?php }?>            
        </form>
    </div>

<!-- END BODY -->
</body>
</html>