<div class="sidebar-scroll" style="overflow: hidden; outline: none;" tabindex="5000">
        <div id="sidebar" class="nav-collapse collapse">
         <div class="navbar-inverse">
            <form class="navbar-search visible-phone">
               <input type="text" class="search-query" placeholder="Search">
            </form>
         </div>
          <ul class="sidebar-menu">
              <li class="sub-menu active">
                  <a class="" href="/Medicrm/default">
                      <i class="icon-dashboard"></i>
                      <span>医库软件CRM管理</span>
                  </a>
              </li>
              <li class="sub-menu" id="khgl">
                  <a href="javascript:;" class="">
                      <i class="icon-male"></i>
                      <span>客户管理</span>
                      <span class="arrow"></span>
                  </a>
                  <ul class="sub">
                      <li id="khxx"><a href="/Medicrm/customerlst">客户信息</a></li>
                      <li id="bfxx"><a class="" href="/Medicrm/visitrecord">拜访信息</a></li>
                      <li id="fkxx"><a class="" href="/Medicrm/feedbacklst">反馈信息</a></li>
                  </ul>
              </li>
              <li class="sub-menu" id="yggl">
                  <a href="javascript:;" class="">
                      <i class="icon-user"></i>
                      <span>员工管理</span>
                      <span class="arrow"></span>
                  </a>
                  <ul class="sub">
                      <li id="ygxx"><a class="" href="/Employee/employee">员工信息</a></li>
                  </ul>
              </li>
              <li class="sub-menu" id="xtsz">
                  <a href="javascript:;" class="">
                      <i class="icon-cogs"></i>
                      <span>系统设置</span>
                      <span class="arrow"></span>
                  </a>
                  <ul class="sub">
                      <li id="xtyx"><a class="" href="/Systemset/sysemail">系统邮箱</a></li>
                      <li id="sjtb"><a class="" href="/Systemset/synchrodata">数据同步</a></li>
                  </ul>
              </li>
          </ul>
      </div>
      </div>