<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>系统邮箱列表</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <script src="/js/jquery-1.4.1.js" type="text/javascript"></script>
   <script src="/js/jquery-1.9.1.min.js" type="text/javascript"></script>
   <script src="/js/DatePicker/WdatePicker.js" type="text/javascript"></script>
   <style type="text/css">
		.searchinput{margin-top:10px;width:100px;}
		.searchselect{margin-top:10px;width:120px;}
   </style>
</head>
<body class="fixed-top">
   <?php require APPLICATION_PATH.'/views/scripts/index/header.phtml';?>
   <div id="container" class="row-fluid">
      <?php require APPLICATION_PATH.'/views/scripts/index/mainleft.phtml';?>
      
      <div id="main-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                   <h3 class="page-title">系统邮箱列表</h3>
                   <ul class="breadcrumb">
                       <li>
                           <a href="/Medicrm/default">首页</a>
                           <span class="divider">/</span>
                       </li>
                       <li>
                           <a href="#">系统设置</a>
                           <span class="divider">/</span>
                       </li>
                       <li class="active">系统邮箱</li>
                   </ul>
               </div>
            </div>
           
            <div id="page-wraper">
                <div class="row-fluid">
                    <div class="span12">
                        <div class="widget blue">
                            <div class="widget-title">
                                <h4><i class="icon-reorder"></i>系统邮箱列表</h4>
                            </div>
                             <div style="margin-left:20px;margin-top:10px;">
                                <a href="/Systemset/sysemailedit" class="btn" style="text-align:center;color:black;width:100px;">添加系统邮箱</a>
       		                 </div>
                            <div class="widget-body">
                                <table class="table table-striped table-bordered table-advance table-hover">
                                    <thead>
                                    <tr>
                                        <th style="text-align:center;"><i class=""></i> 邮箱所属人</th>
                                        <th style="text-align:center;"><i class=""></i> 邮箱账号</th>
                                        <th style="text-align:center;"><i class=""></i> 邮箱状态</th>
                                        <th style="text-align:center;"></th>
                                    </tr>
                                    </thead>
                                    <?php foreach ($this->emaildata as $email){?>
                                    <tr>
                                        <td style="text-align:center;"><?=$email["crm_OwnName"]?></td>
                                        <td style="text-align:center;"><?=$email["crm_EmailAccount"]?></td>
                                        <td style="text-align:center;"><?=$email["crm_EmailState"]==0?"可用":"不可用"?></td>
                                        <td style="text-align:center;">
                                            <a title="编辑" href="/Systemset/sysemailedit?emailid=<?=$email['crm_SystemID']?>"><button class="btn btn-primary"><i class="icon-pencil"></i></button></a>
                                            <a title="删除" onclick="return confirm('确定删除该条信息么？');" href="/Systemset/sysemaildel?emailid=<?=$email['crm_SystemID']?>"><button class="btn btn-danger"><i class="icon-trash "></i></button></a>
                                        </td>
                                    </tr>
                                    <?php }?>
                                </table>
                                <br/>
								<?php if(empty($this->emaildata)){require APPLICATION_PATH.'/views/scripts/index/noticemsg.phtml';}?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>     
         </div>
      </div>
   </div>
   <?php require APPLICATION_PATH.'/views/scripts/index/bottom.phtml';?>
   <script type="text/javascript" src="/js/jquery-ui-1.9.2.custom.min.js"></script>
   <script>
        function loadfun()
        {
        	 $("#xtyx").attr("class", "active");
        	 $("#xtsz").attr("class", "active");
        }
        loadfun();
   </script>
</body>
</html>
</body>
</html>
