
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>客户信息列表</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <script src="/js/jquery-1.4.1.js" type="text/javascript"></script>
   <script src="/js/jquery-1.9.1.min.js" type="text/javascript"></script>
   <script type="text/javascript">
   var s=0;
   $(function(){
	   $("#savemsg").click(function(){ 
		   var zlpaccount = $('#zlpaccount').val();//珍立拍账号
		   var nickname = $('#nickname').val();//昵称
		   var name = $('#name').val();//客户姓名    
		   var gender = $('#gender').val();//性别   
		   var phone = $('#phone').val(); //手机号码
		   var email = $('#email').val(); //邮箱 
		   var depart = $('#depart').val();//科室
		   var ctitle = $('#ctitle').val();  //客户职称
		   var s1 = $("#s1").find("option:selected").text();//省
		   var s2 = $("#s2").find("option:selected").text();//市
		   var hospital = $("#hospital").find("option:selected").text();//医院
		   var type = $("#type").find("option:selected").val();//客户类型
		   var source = $("#source").find("option:selected").val();//客户来源
		   var qq = $('#qq').val();//QQ
		   var wechat = $('#wechat').val();//微信
		   var cid = $('#cid').val(); //客户信息id
		   var phonereg = /^1\d{10}$/; //手机号码正则
		   var emailreg = /^(\w-*\.*)+@(\w-?)+(\.\w{2,})+$/; //邮箱正则
		   
           if(zlpaccount == ""){ //判断珍立拍账号不能为空
         	  $('#fz').show();
         	  return;
           }else{$('#fz').hide();}
           
           if(nickname == ""){ //判断珍立拍昵称不能为空
           	  $('#fnn').show();
           	  return;
             }else{$('#fnn').hide();}
           
           if(name == ""){//判断姓名不能为空
           	  $('#fn').show();
           	  return;
           }else{$('#fn').hide();}
           
           if(gender == -1){//判断性别不能为空
         	  $('#fg').show();
         	  return;
           }else{$('#fg').hide();}
           
           if(s1 == "--省份--" || s2 == "--地级市--"){
	          $('#fp').show();
	          return;
	       }else{$('#fp').hide();}
	       
	       if(hospital == "--请选择医院--"){//医院
	          $('#fh').show();
	          return;
	       }else{$('#fh').hide();}
	       
           if(depart == 0){//判断所在科室不能为空
         	  $('#fd').show();
         	  return;
           }else{$('#fd').hide();}
           
           if(type == "-1"){//客户类型必填
         	  $('#ft').show();
         	  return;
           }else{$('#ft').hide();}
           
           if(source == "-1"){//客户来源必填
         	  $('#fs').show();
         	  return;
           }else{$('#fs').hide();}
           
           if(phone!="")
			{
				if(!phonereg.test(phone))
				{
					alert('手机号码不合法');
					$('#phone').focus();
					return false;
				}
			}
			
			if(email!="")
			{
				if(!emailreg.test(email))
				{
					alert('邮箱不合法');
					$('#email').focus();
					return false;
				}
			}
			
   		   $.ajax({
   	         type: "POST",
   	         url: "/Medicrm/clientmsgsave",
   	         data:"zlpaccount="+zlpaccount+"&nickname="+nickname+"&name="+name+"&gender="+gender+"&phone="+phone+"&email="+email+"&hospital="+hospital+"&depart="+depart+"&ctitle="+ctitle+"&s1="+s1+"&s2="+s2+"&type="+type+"&source="+source+"&qq="+qq+"&wechat="+wechat+"&cid="+cid,
   	         success: function(msg){
       	         if(msg==0){
           	         alert("客户信息添加成功！");          	         
       	         }
       	         else if(msg==1){
        	        alert("客户信息编辑成功！");
       	         }
       	         else{//说明token过期或者token错误，用户需要重新登录
  			       	window.location.href='/Index/index';
  			        return;   
           	     }
          	     window.location.href='/Medicrm/customerlst';
   	         }
   		  });
      });
	      
	   //根据一级省份名获取地级市
	   $('#s1').change(function(){
	       var id = $("#s1").find('option:selected').attr("data-type_name");
	        $.ajax({
	            type: "POST",
	                url: "/Medicrm/changecity",
	                data:"cityid="+id,
	                success: function(msg){
	                 if(msg==0){//说明token过期或者token错误，用户需要重新登录
	           			window.location.href='/Index/index';
	          			return;    
		           	 }else{
			           	var s2 = $("#s2"); 
			            $("option",s2).remove(); //清空原有的选项
	                    var a=eval('('+msg+')');
	                    var option = "<option value='-1'>"+'--地级市--'+"</option>"; 
	                       $.each(a,function(index,array){ 
	                            option+="<option value='"+array['CityName']+"' data-type_name='"+array['CityID']+"'>"+array['CityName']+"</option>";  
	                      }); 
	                    s2.append(option); 
		           	 }
	              }
	         });     
	     })
	     
		 //根据区获取区所属医院列表
		 $('#s2').change(function(){
     	  var id = $("#s2").find('option:selected').attr("data-type_name");
	      $.ajax({
	          type: "POST",
	              url: "/Medicrm/getcityhospital",
	              data:"areaid="+id ,
	              success: function(msg){
	            	if(msg==0){//说明token过期或者token错误，用户需要重新登录
		           		window.location.href='/Index/index';
		          		return;    
			        }else{
		             	var hp = $("#hospital"); 
		                $("option",hp).remove(); //清空原有的选项 
		                var a=eval('('+msg+')');
		                var option="<option value='-1'>"+'--请选择医院--'+"</option>";
		                $.each(a,function(index,array){ 
		                     option += "<option value='"+array['HospitalName']+"'>"+array['HospitalName']+"</option>"; 
		                }); 
		                hp.append(option);
			        } 
	             }
	        });    
    	})
   });  
   </script>
   <style type="text/css">
		.tdinput{margin-top:10px;width:200px;}
		.searchselect{margin-top:10px;width:120px;}
		.fontck{font-size:16px;line-height:30px;}
		.left{text-align:right;}
   </style>
</head>
<body class="fixed-top">
   <?php require APPLICATION_PATH.'/views/scripts/index/header.phtml';?>
   <div id="container" class="row-fluid">
      <?php require APPLICATION_PATH.'/views/scripts/index/mainleft.phtml';?>
      <input type="hidden" id="cid" name="cid" value="<?=$this->clientinfo['crm_ClientID']?>"></input>
      <div id="main-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                   <h3 class="page-title">
                   <?php if(empty($this->ck)){?>
                                                客户信息<?=!empty($this->upd)?"修改":"添加"?>
                    <?php }else{?>
                                                客户信息查看
                    <?php }?>
                   </h3>
                   <ul class="breadcrumb">
                       <li>
                           <a href="/Medicrm/default">首页</a>
                           <span class="divider">/</span>
                       </li>
                       <li>
                           <a href="/Medicrm/customerlst">客户管理</a>
                           <span class="divider">/</span>
                       </li>
                       <li class="active">
                   <?php if(empty($this->ck)){?>
                                                客户信息<?=!empty($this->upd)?"修改":"添加"?>
                    <?php }else{?>
                                                客户信息查看
                    <?php }?>
                       </li>
                   </ul>
               </div>
            </div>
           
            <div id="page-wraper">
                <div class="row-fluid">
                    <div class="span12">
                    <?php if (empty($this->ck)){?>
                        <div class="widget blue">
                            <div class="widget-title">
                                <h4><i class="icon-reorder"></i>客户信息<?=!empty($this->upd)?"修改":"添加"?></h4>
                            </div>
                            <div class="widget-body">
                                <table  style="margin-left:38%;">	
                                    <tr>
                                        <td>珍立拍账号：</td>
                                        <td><input type="text" id="zlpaccount" name="zlpaccount" class="tdinput" value="<?=$this->clientinfo['crm_ZlpAccount']?>"></input>&nbsp;*<font id="fz" style="color:#FF0000;display:none;">珍立拍账号必填</font></td>
                                    </tr>
                                    <tr>
                                        <td>珍立昵称：</td>
                                        <td><input type="text" id="nickname" name="nickname" class="tdinput" value="<?=$this->clientinfo['crm_ZlpNickName']?>"></input>&nbsp;*<font id="fnn" style="color:#FF0000;display:none;">珍立拍昵称必填</font></td>
                                    </tr>
                                    <tr>
                                        <td>客户姓名：</td>
                                        <td><input type="text" id="name" name="name" class="tdinput" value="<?=$this->clientinfo['crm_ClientName']?>"></input>&nbsp;*<font id="fn" style="color:#FF0000;display:none;">客户名称必填</font></td>
                                    </tr>
                                    <tr>
                                    	<td>客户性别：</td>
                                    	<td>
                                        	<select id="gender" name="gender" class="searchselect">
                                   			<option value="-1">--选择性别--</option>
                                   			<option value="0" <?=$this->clientinfo['crm_ClientGender']=="0"?"selected":""?>>女</option>
                                  			<option value="1" <?=$this->clientinfo['crm_ClientGender']=="1"?"selected":""?>>男</option>
                              				</select>
                              				&nbsp;*<font id="fg" style="color:#FF0000;display:none;">请选择性别</font>
                              			</td>
                                    </tr>
                                    <tr>
                                        <td>客户电话：</td>
                                        <td><input type="text" id="phone" name="phone" class="tdinput" value="<?=$this->clientinfo['crm_ClientPhone']?>"></input></td>
                                    </tr>
                                    <tr>
                                        <td>客户邮箱：</td>
                                        <td><input type="text" id="email" name="email" class="tdinput" value="<?=$this->clientinfo['crm_ClientEmail']?>"></input></td>
                                    </tr>
                                    <tr>
                                        <td>所在城市：</td>
                                        <td>
                                        <?php $pro=explode(",",$this->clientinfo['crm_ClientCity']);{?>		
                                        	<select id="s1" name="s1">
												<option value="-1">--省份--</option>
												<?php foreach ($this->ccity as $cc){?>
													<option <?=$pro[0]==$cc['CityName']?"selected":""?> value="<?php echo $cc['CityName']?>" data-type_name="<?=$cc['CityID']?>"><?php echo $cc['CityName']?></option>
												<?php }?>
											</select>
											<select id="s2" name="s2">
												<?php if ($pro[1]==""){?>	
												<option value="-1">--地级市--</option>
												<?php }else{?>
												<option <?=$pro[1]!=""?"selected":""?>><?=$pro[1]?></option>
												<?php }?>
											</select>
											<?php }?>
											&nbsp;*<font id="fp" style="color:#FF0000;display:none;">请选择省市</font>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>所在医院：</td>
                                        <td>
                                        	<select id="hospital" name="hospital">	
                                        		<?php if ($this->clientinfo['crm_ClientHospital']==""){?>			
												<option value="-1">--请选择医院--</option>
												<?php }else{?>
												<option><?=$this->clientinfo['crm_ClientHospital']?></option>
												<?php }?>
											</select>
											&nbsp;*<font id="fh" style="color:#FF0000;display:none;">请选择医院</font>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>所在科室：</td>
                                        <td>
                                        	<select id="depart" name="depart" onchange="changepart();">
                                        		<option value="0">--请选择科室--</option>
	                                        	<?php $s=0;foreach ($this->deplist as $dep){
	                                        	if($this->clientinfo['crm_ClientSection']==$dep['DepName']){$s=1;}?>
	                                        		<option <?=$this->clientinfo['crm_ClientSection']==$dep['DepName']?"selected":""?> value="<?=$dep['ID']?>"><?=$dep['DepName']?></option>
	                                        	<?php }?>
                                        	</select>
                                        	&nbsp;*<font id="fd" style="color:#FF0000;display:none;">请选择科室</font>
										</td>
                                    </tr>
                                    <tr>
                                        <td>客户职称：</td>
                                        <td><input type="text" id="ctitle" name="ctitle" class="tdinput" value="<?=$this->clientinfo['crm_ClientTitle']?>"></input></td>
                                    </tr>
                                      <tr>
                                        <td>客户类型：</td>
                                        <td>
                                        	<select id="type" name="type">
                                        		<option value="-1">--未选择客户类型--</option>
                                        		<option value="0" <?=$this->clientinfo['crm_ClientType']=="0"?"selected":""?>>医生</option>
                                   				<option value="1" <?=$this->clientinfo['crm_ClientType']=="1"?"selected":""?>>护士</option>
                                   				<option value="2" <?=$this->clientinfo['crm_ClientType']=="2"?"selected":""?>>医药行业</option>
                                   				<option value="3" <?=$this->clientinfo['crm_ClientType']=="3"?"selected":""?>>医学生</option>
                                  				<option value="4" <?=$this->clientinfo['crm_ClientType']=="4"?"selected":""?>>赔付宝</option>
                                   				<option value="5" <?=$this->clientinfo['crm_ClientType']=="5"?"selected":""?>>其他人群</option>
                                   				<option value="6" <?=$this->clientinfo['crm_ClientType']=="6"?"selected":""?>>实习医生</option>
                                        	</select>
                                        	&nbsp;*<font id="ft" style="color:#FF0000;display:none;">请选择客户类型</font>
										</td>
                                    </tr>
                                    <tr>
                                        <td>客户来源：</td>
                                        <td>
                                        	<select id="source" name="source">
                                        		<option value="-1">--未选择客户来源--</option>
                                        		<option <?=$this->clientinfo['crm_ClientSource']=="0"?"selected":""?> value="0">珍立拍用户</option>
                                        		<option <?=$this->clientinfo['crm_ClientSource']=="1"?"selected":""?> value="1">睿医用户</option>
                                        		<option <?=$this->clientinfo['crm_ClientSource']=="2"?"selected":""?> value="2">外部合作</option>
                                        		<option <?=$this->clientinfo['crm_ClientSource']=="3"?"selected":""?> value="3">糖医生</option>
                                        	</select>
                                        	&nbsp;*<font id="fs" style="color:#FF0000;display:none;">请选择客户来源</font>
										</td>
                                    </tr>
                                    <tr>
                                        <td>客户QQ：</td>
                                        <td><input type="text" id="qq" name="qq" class="tdinput" value="<?=$this->clientinfo['crm_ClientQQ']?>"></input></td>
                                    </tr>
                                    <tr>
                                        <td>客户微信：</td>
                                        <td><input type="text" id="wechat" name="wechat" class="tdinput" value="<?=$this->clientinfo['crm_WeChat']?>"></input></td>
                                    </tr>
                                    <tr>
                                    	<td align="right">
                                    		<a href="javascript:void(0)" class="btn" style="text-align:center;color:black;width:50px;" id="savemsg">保存</a>
                                    	</td>
                                    	<td align="left">
                                    		<a href="/Medicrm/customerlst" class="btn" style="text-align:center;color:black;width:50px;margin-left:100px;">返回</a>
                                    	</td>
                                    </tr>
                                    
                                </table>
                            </div>
                        </div>
                        <?php }else{?>
                        	<div class="widget blue">
                            <div class="widget-title">
                                <h4><i class="icon-reorder"></i>客户信息查看</h4>
                            </div>
                            <div class="widget-body">
                                <table  style="margin-left:38%;">	
                                    <tr class="fontck">
                                        <td class="left">珍立拍账号：</td>
                                        <td><?=$this->clientinfo['crm_ZlpAccount']?></td>  
                                    </tr>
                       
                                    <tr class="fontck">
                                        <td class="left">珍立拍昵称：</td>
                                        <td><?=$this->clientinfo['crm_ZlpNickName']?></td>
                                    </tr>
                                    <tr class="fontck">
                                        <td class="left">客户姓名：</td>
                                        <td><?=$this->clientinfo['crm_ClientName']?></td>
                                    </tr>
                                    <tr class="fontck">
                                    	<td class="left">客户性别：</td>
                                    	<td><?=$this->clientinfo['crm_ClientGender']==0?"女":"男"?></td>
                                    </tr>
                                    <tr class="fontck">
                                        <td class="left">客户电话：</td>
                                        <td><?=$this->clientinfo['crm_ClientPhone']?></td>
                                    </tr>
                                    <tr class="fontck">
                                        <td class="left">客户邮箱：</td>
                                        <td><?=$this->clientinfo['crm_ClientEmail']?></td>
                                    </tr>
                                    <tr class="fontck">
                                        <td class="left">所在城市：</td>
                                        <td><?=$this->clientinfo['crm_ClientCity']?></td>
                                    </tr>
                                    <tr class="fontck">
                                        <td class="left">所在医院：</td>
                                        <td><?=$this->clientinfo['crm_ClientHospital']?></td>
                                    </tr>
                                    <tr class="fontck">
                                        <td class="left">所在科室：</td>
                                        <td><?=$this->clientinfo['crm_ClientSection']?></td>
                                    </tr>
                                    <tr class="fontck">
                                        <td class="left">客户职称：</td>
                                        <td><?=$this->clientinfo['crm_ClientTitle']?></td>
                                    </tr>
                                      <tr class="fontck">
                                        <td class="left">客户类型：</td>
                                        <td><?php if($this->clientinfo["crm_ClientType"]==0){echo "医生";}elseif ($this->clientinfo["crm_ClientType"]==1){echo "护士";}
                                        elseif ($this->clientinfo["crm_ClientType"]==2){echo "医药行业";}elseif ($this->clientinfo["crm_ClientType"]==3){echo "医学生";}elseif ($this->clientinfo["crm_ClientType"]==4){echo "赔付宝";}
                                    elseif ($this->clientinfo["crm_ClientType"]==5){echo "其他人群";}elseif ($this->clientinfo["crm_ClientType"]==6){echo "护士";}?></td>
                                    </tr>
                                    <tr class="fontck">
                                        <td class="left">客户来源：</td>
                                        <td><?php if($this->clientinfo["crm_ClientSource"]==0){echo "珍立拍用户";}elseif ($this->clientinfo["crm_ClientSource"]==1){echo "睿医用户";}
                                        elseif ($this->clientinfo["crm_ClientSource"]==2){echo "外部合作";}elseif ($this->clientinfo["crm_ClientSource"]==3){echo "实习医生";}?></td>
                                    </tr>
                                    <tr class="fontck">
                                        <td class="left">客户QQ：</td>
                                        <td><?=$this->clientinfo['crm_ClientQQ']?></td>
                                    </tr>
                                    <tr class="fontck">
                                        <td class="left">客户微信：</td>
                                        <td><?=$this->clientinfo['crm_WeChat']?></td>
                                    </tr>                                    
                                </table>
                                <div style="margin-left:35%; line-height:50px;">
                                	<a href="/Medicrm/customerlst" class="btn" style="text-align:center;color:black;width:50px;margin-left:100px;">返回</a>
                                </div>
                            </div>
                        </div>
                        <?php }?>
                    </div>
                </div>

            </div>     
         </div>
      </div>
   </div>
   <?php require APPLICATION_PATH.'/views/scripts/index/bottom.phtml';?>
   <script type="text/javascript" src="/js/jquery-ui-1.9.2.custom.min.js"></script>
   <script>
        function loadfun()
        {
        	 $("#khxx").attr("class", "active");
        	 $("#khgl").attr("class", "active");
        }
        loadfun();
   </script>
</body>
</html>
