
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>反馈信息列表</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <script src="/js/jquery-1.4.1.js" type="text/javascript"></script>
   <script src="/js/jquery-1.9.1.min.js" type="text/javascript"></script>
   <script src="/js/DatePicker/WdatePicker.js" type="text/javascript"></script>
   <script type="text/javascript">
	   
		function searchuserinfo()
		{
		   var statime = $('#statime').val();
		   var endtime = $("#endtime").val();
		   var name=$('#name').val();
		   if(statime!=""&&endtime=="")
		   {
			   alert("请选择结束日期！");return;
		   }
		   if(statime==""&&endtime!="")
		   {
			   alert("请选择开始日期！");return;
		   }
		   window.location.href="/Medicrm/feedbacklst?statime="+statime+"&endtime="+endtime+"&name="+name;
		}
		//删除信息
		function feedbackdel(fid)
		{
			if(confirm("确定要删除该条信息吗？")){
				 $.ajax({
					  	type: "POST",
					    url: "/Medicrm/feedbackdel",
					    data:"fid="+fid,
					    success: function(msg){
					    if(msg==0){
					        alert("删除信息成功！");
				        }
					    else
			         	{
			         	    alert("删除失败！");
			            }
					    window.location.href='/Medicrm/feedbacklst';
					}
				});
			}
		}
   </script>
   <style type="text/css">
		.searchinput{margin-top:10px;width:100px;}
		.searchselect{margin-top:10px;width:120px;}
   </style>
</head>
<body class="fixed-top">
   <?php require APPLICATION_PATH.'/views/scripts/index/header.phtml';?>
   <div id="container" class="row-fluid">
      <?php require APPLICATION_PATH.'/views/scripts/index/mainleft.phtml';?>
      
      <div id="main-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                   <h3 class="page-title">反馈信息</h3>
                   <ul class="breadcrumb">
                       <li>
                           <a href="/Medicrm/default">首页</a>
                           <span class="divider">/</span>
                       </li>
                       <li>
                           <a href="/Medicrm/feedbacklst">反馈信息管理</a>
                           <span class="divider">/</span>
                       </li>
                       <li class="active">反馈信息</li>
                   </ul>
               </div>
            </div>
           
            <div id="page-wraper">
                <div class="row-fluid">
                    <div class="span12">
                        <div class="widget blue">
                            <div class="widget-title">
                                <h4><i class="icon-reorder"></i>反馈信息列表&nbsp;&nbsp;	<b><?= $this->lbcount?>&nbsp;条</b></h4>
                            </div>
                <div style="margin-left:20px;">
                <table>
                  <tr>
                  		<td>
                            &nbsp;<b>选择日期：</b>
                        </td>
						<td colspan="3">
                            <input type="text" size="10" onclick="WdatePicker();" name="statime" id="statime" value="<?php echo $this->selarr['statime'];?>" class="searchinput"></input>&nbsp;至&nbsp;<input type="text" size="10" onclick="WdatePicker();" name="endtime" id="endtime" value="<?php echo $this->selarr['endtime'];?>" class="searchinput"></input>
                        </td>
                        <td>
                            &nbsp;<b>客户姓名：</b>
                        </td>
                        <td>
                            <input type="text" id="name" name="name" class="searchinput" value="<?=$this->selarr['name']?>" />
                        </td>
                        <td>
                            &nbsp;&nbsp;&nbsp;
                            <a href="javascript:void(0)" class="btn" style="text-align:center;color:black;width:80px;" onclick="searchuserinfo();">查询</a>
                        </td>
                    </tr>
                </table>
           		 </div>
                            <div class="widget-body">
                                <table class="table table-striped table-bordered table-advance table-hover">
                                    <thead>
                                    <tr>                   
                                        <th style="text-align:center;"><i class=""></i> 客户姓名</th>
                                        <th style="text-align:center;"><i class=""></i> 反馈摘要</th>
                                        <th style="text-align:center;"><i class=""></i> 反馈日期</th>
                                        <th style="text-align:center;"></th>
                                    </tr>
                                    </thead>
                                    <?php foreach ($this->feedbacklst as $feed){?>
                                    <tr>
                                        <td style="text-align:center;"><?=$feed["crm_ClientName"]?></td>
                                        <td style="text-align:center;"><?=@mb_substr(strip_tags($feed["crm_VisitMsg"],'strong'),0,30,'utf-8').'..';?></td>
                                        <td style="text-align:center;"><?=$feed["crm_VisitTime"]?></td>
                                        <td style="text-align:center;">
                                         	<a title="查看" href="/Medicrm/feedbackdetail?upd=<?=$feed['crm_ID']?>&ck=1"><button class="btn btn-success"><i class="icon-edit"></i></button></a>
                                            <a title="编辑" href="/Medicrm/feedbackdetail?upd=<?=$feed['crm_ID']?>"><button class="btn btn-primary"><i class="icon-pencil"></i></button></a>
                                            <a title="删除" onclick="feedbackdel(<?=$feed['crm_ID']?>);" href="javascript:void(0);"><button class="btn btn-danger"><i class="icon-trash "></i></button></a>
                                        </td>
                                    </tr>
                                    <?php }?>
                                </table>
                                <br/>
                                <?php if ($this->lbcount>10){
								 	require APPLICATION_PATH.'/views/scripts/index/pageclass.php';
								 	$p=new PageClass();
								 	$pagemsg=$p->pagemsg($this->spage,$this->cpage,"/Medicrm/feedbacklst",$this->$urlpara);
									}
									echo "<div style='width:90%;margin:0 auto;text-align:right;'$pagemsg</div>";
								 ?> 
								<?php if ($this->lbcount<=0){
									require APPLICATION_PATH.'/views/scripts/index/noticemsg.phtml';
									}
								?>
                             
                            </div>
                        </div>
                    </div>
                </div>
            </div>     
         </div>
      </div>
   </div>
   <?php require APPLICATION_PATH.'/views/scripts/index/bottom.phtml';?>
   <script type="text/javascript" src="/js/jquery-ui-1.9.2.custom.min.js"></script>
   <script>
        function loadfun()
        {
        	 $("#fkxx").attr("class", "active");
        	 $("#khgl").attr("class", "active");
        }
        loadfun();
   </script>
</body>
</html>
