
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>反馈信息</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <script src="/js/jquery-1.4.1.js" type="text/javascript"></script>
   <script src="/js/jquery-1.10.2.js" type="text/javascript"></script>
   <script src="/js/DatePicker/WdatePicker.js" type="text/javascript"></script>
   <script src="/js/jquery-ui.js" type="text/javascript"></script>
   <link rel="stylesheet" href="/css/jquery-ui.css" />
   <script type="text/javascript">
   $(function(){
	   	 var usernameTags=[];	   
		 $.ajax({
				type:"POST",
				url:"/Medicrm/lstuser",
				data:"",
				success:function(msg){
					var a =eval('('+msg+')');		
					$.each(a,function(index,array){
						usernameTags.push(array['crm_ClientName']);
					});     
				}
		 });
		
		$("#usersh").autocomplete({
			//自定义匹配条件，从首字母匹配
			source: function( request, response ) {
	          var matcher = new RegExp( "^" + $.ui.autocomplete.escapeRegex( request.term ), "i" );
	          response( $.grep( usernameTags, function( item ){
	              return matcher.test( item );
	          }) );
	      }
		});
	   $("#savemsg").click(function(){ 
		   var name=$('#usersh').val();//客户姓名   
		   var fabstract=$("#abstract").val();//反馈摘要 
		   var content=$('#content').val();//反馈内容
		   var ftime=$("#ftime").val();//反馈时间
		   var floginuser=$('#floginuser').val();//记录人  
		   var fid=$('#fid').val();
		   if(name=="")
		   {
			   alert("请填写客户姓名");return;
		   }
   		   $.ajax({
   	         type: "POST",
   	         url: "/Medicrm/feedbacksave",
   	         data:"name="+name+"&fabstract="+fabstract+"&content="+content+"&ftime="+ftime+"&floginuser="+floginuser+"&fid="+fid,
   	         success: function(msg){
       	         if(msg==1){
        	        alert("反馈信息编辑成功！");
       	         }
       	         else if(msg==2){
           	         alert("该客户名称不存在，请重新输入！");
           	         return;
           	     }
          	     else if(msg==3){
         	         alert("该提交人名称不存在，请重新输入！");
         	         return;
         	     }
          	     window.location.href='/Medicrm/feedbacklst';
   	         }
   		  });
      });
   });  
   </script>
   <style type="text/css">
		.tdinput{margin-top:10px;width:200px;}
		.searchselect{margin-top:10px;width:215px;}
		.fontck{font-size:16px;line-height:30px;}
		.ui-autocomplete {
		    max-height: 150px;
		    overflow-y: auto;
		    /* 防止水平滚动条 */
		    overflow-x: hidden;
		  }
		  /* IE 6 不支持 max-height
		   * 我们使用 height 代替，但是这会强制菜单总是显示为那个高度
		   */
		  * html .ui-autocomplete {
		    height: 150px;
		  }
   </style>
</head>
<body class="fixed-top">
   <?php require APPLICATION_PATH.'/views/scripts/index/header.phtml';?>
   <div id="container" class="row-fluid">
      <?php require APPLICATION_PATH.'/views/scripts/index/mainleft.phtml';?>
      <input type="hidden" id="fid" name="fid" value="<?=$this->feedbackinfo['crm_ID']?>"></input>
      <div id="main-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE HEADER-->  
            <?php if (empty($this->ck)){?> 
            <div class="row-fluid">
               <div class="span12">
                   <h3 class="page-title">反馈信息修改</h3>
                   <ul class="breadcrumb">
                       <li>
                           <a href="/Medicrm/default">首页</a>
                           <span class="divider">/</span>
                       </li>
                       <li>
                           <a href="/Medicrm/visitrecord">反馈信息管理</a>
                           <span class="divider">/</span>
                       </li>
                       <li class="active">反馈信息修改</li>
                   </ul>
               </div>
            </div>
           
            <div id="page-wraper">
                <div class="row-fluid">
                    <div class="span12">
                        <div class="widget blue">
                            <div class="widget-title">
                                <h4><i class="icon-reorder"></i>反馈信息修改</h4>
                            </div>
                            <div class="widget-body">
                                <table  style="margin-left:38%;">
                                    <tr>
                                        <td>客户姓名：</td>
                                        <td>
                                        	<input type="text" id="usersh" name="usersh" value="<?=$this->feedbackinfo['crm_ClientName']?>" class="tdinput" readonly="readonly"/>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>反馈摘要：</td>
                                        <td>
                                        	<input type="text" id="abstract" name="abstract" value="<?=$this->feedbackinfo['crm_VisitMsg']?>" class="tdinput"/>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>反馈内容：</td>
                                        <td>
                                        	<textarea id="content" name="content"  class="tdinput" style="height:100px;"><?=$this->feedbackinfo['crm_VisitBackMsg']?></textarea>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>反馈日期：</td>
                                        <td><input type="text" size="10"  name="ftime" id="ftime" value="<?=$this->feedbackinfo['crm_VisitTime']?>" class="tdinput" readonly="readonly"/></td>
                                    </tr>
                                    <tr>
                                        <td>记录人：</td>
                                        <td><input type="text" id="floginuser" value="<?=$_SESSION['loginuser']['crm_LoginName'] ?>" readonly="readonly"/>
                                        </td>
                                    </tr>
                                    <tr>
                                    	<td align="right">
                                    		<a href="javascript:void(0)" class="btn" style="text-align:center;color:black;width:50px;" id="savemsg">保存</a>
                                    	</td>
                                    	<td align="left">
                                    		<a href="javascript:history.go(-1);" class="btn" style="text-align:center;color:black;width:50px;margin-left:100px;">返回</a>
                                    	</td>
                                    </tr>
                                    
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
            <?php }else{?>
             <div class="row-fluid">
               <div class="span12">
                   <h3 class="page-title">反馈信息查看</h3>
                   <ul class="breadcrumb">
                       <li>
                           <a href="/Medicrm/default">首页</a>
                           <span class="divider">/</span>
                       </li>
                       <li>
                           <a href="/Medicrm/feedbacklst">反馈信息管理</a>
                           <span class="divider">/</span>
                       </li>
                       <li class="active">反馈信息查看</li>
                   </ul>
               </div>
            </div>
           
            <div id="page-wraper">
                <div class="row-fluid">
                    <div class="span12">
                        <div class="widget blue">
                            <div class="widget-title">
                                <h4><i class="icon-reorder"></i>反馈信息查看</h4>
                            </div>
                            <div class="widget-body">
                                <table  style="margin-left:38%;">
                                    <tr class="fontck">
                                        <td style="width:10%;">客户姓名：</td>
                                        <td>
                                        	<font><?=$this->feedbackinfo['crm_ClientName']?></font>
                                        </td>
                                    </tr>
                                    <tr class="fontck">
                                        <td style="width:10%;">联系电话：</td>
                                        <td>
                                        	<font><?=$this->feedbackinfo['crm_ClientPhone']?></font>
                                        </td>
                                    </tr>
                                    <tr class="fontck">
                                        <td style="width:10%;">客户邮箱：</td>
                                        <td>
                                        	<font><?=$this->feedbackinfo['crm_ClientEmail']?></font>
                                        </td>
                                    </tr>
                                    <tr class="fontck">
                                        <td style="width:10%;">反馈摘要：</td>
                                        <td>
                                        	<font><?=$this->feedbackinfo['crm_VisitMsg']?></font>
                                        </td>
                                    </tr>
                                     <tr class="fontck">
                                        <td style="width:10%;">反馈内容：</td>
                                        <td>
                                        	<font><?=$this->feedbackinfo['crm_VisitBackMsg']?></font>
                                        </td>
                                    </tr>
                                    <tr class="fontck">
                                        <td style="width:10%;">反馈日期：</td>
                                        <td>
                                        	<font><?=$this->feedbackinfo['crm_VisitTime']?></font>
                                        </td>
                                    </tr>
                                    <tr style="line-height:50px;">
                                    	<td style="text-align:left;" colspan="2">
                                    		<a href="javascript:history.go(-1);" class="btn" style="text-align:center;color:black;width:50px;margin-left:40px;">返回</a>
                                    	</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
            <?php }?>  
         </div>
      </div>
   </div>
   <?php require APPLICATION_PATH.'/views/scripts/index/bottom.phtml';?>
   
   <script>
        function loadfun()
        {
        	 $("#fkxx").attr("class", "active");
        	 $("#khgl").attr("class", "active");
        }
        loadfun();
   </script>
</body>
</html>
