
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>邮件发送</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <script src="/js/jquery-1.10.2.js" type="text/javascript"></script>
   <script src="/js/DatePicker/WdatePicker.js" type="text/javascript"></script>
   <script type="text/javascript">
   $(function(){
	   $("#savemsg").click(function(){ 
		   var clientname=$('#clientname').val();//收件人   
		   var subject=$('#subject').val();//主题
		   var textfield=$('#textfield').val();//附件
		   var datacountent=UE.getEditor('container1').getContentTxt();//正文
		   if(clientname=="")
		   {
			   alert("收件人不能为空！");return;
		   }
		   if(subject=="")
		   {
			   alert("邮件主题不能为空！");return;
		   }
		   if(textfield==""&&datacountent=="")
		   {
			   alert("附件和正文不能都为空！");return;
		   }
		   document.mform.action="/Medicrm/emailsave";
		   document.mform.target="";
		   document.mform.submit();
      });
   });  
   </script>
   <style type="text/css">
		.tdinput{margin-top:10px;width:500px;}
		.fontck{font-size:16px;line-height:30px;}
		.file-box{ position:relative;width:660px;padding-bottom:10px;} 
		.txt{ border:1px solid #cdcdcd; width:400px;} 
		.file{  cursor: pointer; height: 32px;opacity: 0;position: absolute;right: 200px;width: 80px;top:0; filter:alpha(opacity:0);opacity: 0;}
   </style>
</head>
<body class="fixed-top">
   <?php require APPLICATION_PATH.'/views/scripts/index/header.phtml';?>
   <div id="container" class="row-fluid">
      <?php require APPLICATION_PATH.'/views/scripts/index/mainleft.phtml';?>
      <div id="main-content">
      <form name="mform" method="post"enctype="multipart/form-data">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE HEADER-->  
            <div class="row-fluid">
               <div class="span12">
                   <h3 class="page-title">发送邮件</h3>
                   <ul class="breadcrumb">
                       <li>
                           <a href="/Medicrm/default">首页</a>
                           <span class="divider">/</span>
                       </li>
                       <li>
                           <a href="/Medicrm/sendmaillst">已发邮件管理</a>
                           <span class="divider">/</span>
                       </li>
                       <li class="active">发送邮件</li>
                   </ul>
               </div>
            </div>
           
            <div id="page-wraper">
                <div class="row-fluid">
                    <div class="span12">
                        <div class="widget blue">
                            <div class="widget-title">
                                <h4><i class="icon-reorder"></i>发送邮件</h4>
                            </div>
                            <div class="widget-body">
                                <table  style="">
                                    <tr>
                                        <td>收件人：</td>
                                        <td>
                                        	<input type="text" id="clientname" name="clientname" class="tdinput" value="<?=$this->username?>"></input>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>主题：</td>
                                        <td><input type="text" id="subject" name="subject" class="tdinput"></input>
                                        </td>
                                    </tr>
				                    <tr>
				                        <td class="right" height="30">附件上传：</td>
										<td><div class="file-box">
											<input type='text' name='textfield' id='textfield' class='txt' value=""/> 
											<input type='button' class='btn' value='浏览...' /> 
											<input type="file" name="cousefile" class="file" id="cousefile" size="28" onchange="document.getElementById('textfield').value=this.value" /> 
										</div> 
										</td>
				                    </tr>
                                    <tr>
                                        <td>正文：</td>          
                                        <td align="center">
							  			<script id="container1" name="datacountent" type="text/plain" style="width:700px;height:200px;">

    									</script>
										<!-- 配置文件 -->
										<script type="text/javascript" src="/ueditor/ueditor.config.js"></script>
										<!-- 编辑器源码文件 -->
										<script type="text/javascript" src="/ueditor/ueditor.all.js"></script>
							   		    <!-- 实例化编辑器 -->
										<script type="text/javascript">
							       			 var ue = UE.getEditor('container1',{autoHeightEnabled:false});
							   		    </script>
										</td>
                                    </tr>
                                   
                                    <tr>
                                    	<td align="right">
                                    	</td>
                                    	<td align="left">
                                    		<a href="javascript:void(0)" class="btn" style="text-align:center;color:black;width:50px;margin:20px 0 0 100px;" id="savemsg">发送</a>    	
                                    		<a href="javascript:history.go(-1);" class="btn" style="text-align:center;color:black;width:50px;margin-left:100px;margin-top:20px;">返回</a>
                                    	</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
         </div>
         </form>
      </div>
   </div>
   <?php require APPLICATION_PATH.'/views/scripts/index/bottom.phtml';?>
   <script type="text/javascript" src="/js/jquery-ui-1.9.2.custom.min.js"></script>
   <script>
	    function loadfun()
	    {
	   	  $("#khxx").attr("class", "active");
	   	  $("#khgl").attr("class", "active");
	    }
        loadfun();
   </script>
</body>
</html>
