
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>回访信息列表</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <script src="/js/jquery-1.4.1.js" type="text/javascript"></script>
   <script src="/js/jquery-1.9.1.min.js" type="text/javascript"></script>
   <script src="/js/DatePicker/WdatePicker.js" type="text/javascript"></script>
   <script type="text/javascript">
		function searchuserinfo()
		{
		   var statime = $('#statime').val();
		   var endtime = $("#endtime").val();
		   var name=$('#name').val();
		   if(statime!=""&&endtime=="")
		   {
			   alert("请选择结束日期！");
			   return false;
		   }
		   if(statime==""&&endtime!="")
		   {
			   alert("请选择开始日期！");
			   return false;
		   }
		}
		//查询，添加拜访，导出excel，post提交到不同控制器
		function submitchaxun(){
			document.forms["form"].action="/Medicrm/visitrecord";
			document.forms["form"].submit();
			}
		function submitbaifang(){
			document.forms["form"].action="/Medicrm/visitdetail";
			document.forms["form"].submit();
			}
		function submitdaochu(){
			document.forms["form"].action="/Medicrm/excelexport";
			document.forms["form"].submit();
			}
   </script>
   <style type="text/css">
		.searchinput{margin-top:10px;width:100px;}
		.searchselect{margin-top:10px;width:120px;}
   </style>
</head>
<body class="fixed-top">
<?php 
	$visittype=array(
		"0"=>"短信",
		"1"=>"邮件",
		"2"=>"电话",
		"3"=>"实体"
	);
?>
   <?php require APPLICATION_PATH.'/views/scripts/index/header.phtml';?>
   <div id="container" class="row-fluid">
      <?php require APPLICATION_PATH.'/views/scripts/index/mainleft.phtml';?>
      
      <div id="main-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                   <h3 class="page-title">拜访信息</h3>
                   <ul class="breadcrumb">
                       <li>
                           <a href="/Medicrm/default">首页</a>
                           <span class="divider">/</span>
                       </li>
                       <li>
                           <a href="/Medicrm/visitrecord">拜访信息管理</a>
                           <span class="divider">/</span>
                       </li>
                       <li class="active">拜访信息</li>
                   </ul>
               </div>
            </div>
           
            <div id="page-wraper">
                <div class="row-fluid">
                    <div class="span12">
                        <div class="widget blue">
                            <div class="widget-title">
                                <h4><i class="icon-reorder"></i>拜访信息列表&nbsp;&nbsp;	<b><?= $this->lbcount?>&nbsp;条</b></h4>
                            </div>
                <div style="margin-left:20px;">
                <form method="post" id="form">
               			 <p>
                            &nbsp;<b>选择日期：</b>
                            <input type="text" size="10" onclick="WdatePicker();" name="statime" id="statime" value="<?php echo $this->selarr['statime'];?>" class="searchinput"></input>&nbsp;至&nbsp;<input type="text" size="10" onclick="WdatePicker();" name="endtime" id="endtime" value="<?php echo $this->selarr['endtime'];?>" class="searchinput"></input>
                        
                            &nbsp;<b>客户姓名：</b>
                            <input type="text" id="name" name="name" class="searchinput" value="<?=$this->selarr['name']?>" />
                    
                           &nbsp;<b>拜访类型：</b>
                            <select id="vtype" name="vtype" class="searchselect">
                           		<option value="-1">全部</option>
                            	<option value="0" <?=$this->selarr['vtype']=="0"?"selected":""?>>短信</option>
                            	<option value="1" <?=$this->selarr['vtype']=="1"?"selected":""?>>邮件</option>
                            	<option value="2" <?=$this->selarr['vtype']=="2"?"selected":""?>>电话</option>
                            	<option value="3" <?=$this->selarr['vtype']=="3"?"selected":""?>>实体</option>
                            </select>
                            &nbsp;&nbsp;&nbsp;
                            <a href='javascript:submitchaxun();' class="btn" style="text-align:center;color:black;width:80px;" onclick="searchuserinfo();">查询</a>
                            &nbsp;&nbsp;&nbsp;
                            <a href='javascript:submitbaifang();' class="btn" style="text-align:center;color:black;width:80px;">添加拜访</a>
                            &nbsp;&nbsp;&nbsp;	                       
                       		<a href='javascript:submitdaochu();' class="btn" style="text-align:center;color:black;width:80px;" >导出excel</a>
                       		</p>
					</form>
           		 </div>
                            <div class="widget-body">
                                <table class="table table-striped table-bordered table-advance table-hover">
                                    <thead>
                                    <tr>
                                        <th style="text-align:center;"><i class=""></i> 拜访客户</th>
                                        <th style="text-align:center;"><i class=""></i> 拜访方式</th>
                                        <th style="text-align:center;"><i class=""></i> 拜访主题</th>
                                        <th style="text-align:center;"><i class=""></i> 拜访时间</th>
                                        <th style="text-align:center;"><i class=""></i> 拜访状态</th>
                                        <th style="text-align:center;"></th>
                                    </tr>
                                    </thead>
                                    <?php foreach ($this->visitlst as $visit){?>
                                    <tr>
                                        <td style="text-align:center;"><?=$visit["crm_ClientName"]?></td>
                                        <td style="text-align:center;"><?=$visittype[$visit["crm_VisitType"]]?></td>
                                        <td style="text-align:center;"><?=$visit["crm_VisitMsg"]?></td>
                                        <td style="text-align:center;"><?=$visit["crm_VisitTime"]?></td>
                                        <td style="text-align:center;"><?=empty($visit["crm_VisitStatus"])?"未拜访":"已拜访"?></td>
                                        <td style="text-align:center;">
                                            <a title="查看" href="/Medicrm/visitdetail?upd=<?=$visit['crm_ID']?>&ck=1"><button class="btn btn-success"><i class="icon-edit"></i></button></a>
                                            <a title="编辑" href="/Medicrm/visitdetail?upd=<?=$visit['crm_ID']?>"><button class="btn btn-primary"><i class="icon-pencil"></i></button></a>
                                            <a title="删除" onclick="return confirm('确定删除该条信息么？');" href="/Medicrm/visitdel?cid=<?=$visit['crm_ID']?>"><button class="btn btn-danger"><i class="icon-trash "></i></button></a>
                                        </td>
                                    </tr>
                                    <?php }?>
                                </table>
                                <br/>
								<?php if ($this->lbcount>10){
								 	require APPLICATION_PATH.'/views/scripts/index/pageclass.php';
								 	$p=new PageClass();
								 	$pagemsg=$p->pagemsg($this->spage,$this->cpage,"/Medicrm/visitrecord",$this->urlpara);
									}
									echo "<div style='width:90%;margin:0 auto;text-align:right;'>$pagemsg</div>";
								 ?> 
								<?php if ($this->lbcount<=0){
									require APPLICATION_PATH.'/views/scripts/index/noticemsg.phtml';
									}
								?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>     
         </div>
      </div>
   </div>
   <?php require APPLICATION_PATH.'/views/scripts/index/bottom.phtml';?>
   <script type="text/javascript" src="/js/jquery-ui-1.9.2.custom.min.js"></script>
   <script>
        function loadfun()
        {
        	 $("#bfxx").attr("class", "active");
        	 $("#khgl").attr("class", "active");
        }
        loadfun();
   </script>
</body>
</html>
