<!DOCTYPE html>
<head>
   <meta charset="utf-8" />
   <title>医库CRM管理出错</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="" name="author" />
   <link href="/css/bootstrap.min.css" rel="stylesheet" />
   <link href="/css/font-awesome.css" rel="stylesheet" />
   <link href="/css/style.css" rel="stylesheet" />
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="error-404">
    <div class="error-wrap error-wrap-404">
        <div class="metro big terques">
           <span> OOPS! </span>
        </div>
        <div class="metro green">
            <span> 4 </span>
        </div>
        <div class="metro yellow">
            <span> 0 </span>
        </div>
        <div class="metro purple">
            <span> 4 </span>
        </div>
        <div class="metro double red">
            <span class="page-txt"> Page Not Found </span>
        </div>
        <div class="metro gray">
            <a href="/Medicrm/default" class="home" title="返回首页"><i class="icon-home"></i> </a>
        </div>

    </div>
</body>
<!-- END BODY -->
</html>
